// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alujthtoohcpyrdwewuo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsdWp0aHRvb2hjcHlyZHdld3VvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNDY0NjYsImV4cCI6MjA2NzkyMjQ2Nn0.kTmUowvCDYBN_rRIhT8F0-1fG_V7lhaFBwa3cDd0ZgU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});